### ISSUE TITLE
Profile View Controller for Users

### ISSUE THREAD

**Issue by ilanashapiro** [mloirraqi/Dorm-a-Shop#8]
- Tab bar design, where other tab is all posts view controller

**Comment by addisonn** [comment]
able to change status for items when sold

**Comment by ilanashapiro** [comment]
User profile at top of page

**Comment by ilanashapiro** [comment]
Filter by item type/category

**Comment by addisonn** [comment]
Able to click on user's profile pic/username to go to their profile

**Comment by addisonn** [comment]
display list of sold/active items on the profile page
